<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
/**
 * Implements hook_mail().
 */
function custom_login_mail($key, &$message, $params) {
  switch ($key) {
    case 'otp_verification':
      $message['subject'] = $params['subject'];

      $message['body'][] = $params['message'];
      break;
      
    case 'student_notification':
      $message['subject'] = $params['subject'];

      $message['body'][] = $params['message'];
      break;

    case 'admin_notification':
      $message['subject'] = $params['subject'];

      $message['body'][] = $params['message'];
      break;
  }
}

function custom_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $url = Url::fromRoute('custom_login.user_check')->toString();
    $response = new RedirectResponse($url);
    $response->send();
    exit;
  }
}
